### ISSUE TITLE
Spec Flag/Json Missing

### ISSUE THREAD

**Issue by owenrog** [SamLau95/nbinteract#74]
Hi,
Getting the following output when I run nbinteract.publish('owenrog/nbinteract-image/master', 'cow.ipynb') from a cell. However, the following works in CLI: nbinteract -s "owenrog/nbinteract-image/master" cow.ipynb. 
....
Saving notebook... Saved 'cow.ipynb'.
Converting notebook...
WARNING:root:
Error when converting :(

Double check that you didn't misspell your filename. This is the filename you
wanted to publish: cow.ipynb.

If you believe this is an error with the package, please report an issue at
https://github.com/SamLau95/nbinteract/issues/new and include the error output
below:

==============

[nbinteract] --spec flag not set and no .nbinteract.json file found. Rerun this
[nbinteract]   command with the --spec flag or run `nbinteract init` to resolve
[nbinteract]   this issue.
Usage:
  nbinteract init
  nbinteract NOTEBOOKS ...
  nbinteract [options] NOTEBOOKS ...
  nbinteract (-h | --help)

**Comment by SamLau95** [comment]
Oh snap, looks like a bug in the `publish` method. Thanks for the catch, I'll take a look soon!

**Comment by andrzejQ** [comment]
I have the same problem... (Py.3.6.5, Anaconda 5.4)

**Comment by SamLau95** [comment]
Should be fixed in #85. Lemme know if you still run into this error.

**Comment by StrgFJojo** [comment]
I still get this output... 

[nbinteract] --spec flag not set and no .nbinteract.json file found. Rerun this
[nbinteract] command with the --spec flag or run nbinteract init to resolve
[nbinteract] this issue.
Usage:
nbinteract init
nbinteract NOTEBOOKS ...
nbinteract [options] NOTEBOOKS ...
nbinteract (-h | --help)
